arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin #kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0001
  kinematics_solver_timeout: 0.125
  kinematics_solver_attempts: 6
